### ISSUE TITLE
работа со сторонними библиотеками

### ISSUE THREAD

**Issue by Aetet** [ymaps/modules#36]
Привет. Есть ли в модульной системе возможность работать с библиотеками которые не имеют синтаксиса ymaps/modules? Например библиотеки backbone, momentjs. Есть ли аналог shims из AMD, который бы позволял использовать эти библиотеки?

**Comment by Guria** [comment]
@zxqfox
> https://github.com/factorymn/bem-factory/blob/753e622c17518e51c797420f0deb105be0cf2cb9/common.blocks/jquery/__ui/jquery__ui.browser.js

У меня этот способ работает только при наличии jQuery в window. Как библиотеке подсунуть jquery уже загруженный в ymodules?

**Comment by Guria** [comment]
Пока сделал так:
```js
var jQuery;

modules.define(
  'kendo',
  ['loader_type_js', 'jquery'],
  function(provide, loader, $) {
    jQuery = $;
    function doProvide(kendo){
      provide(kendo);
      delete window.jQuery;
      delete window.kendo;
    }
    typeof kendo !== 'undefined'?
        doProvide(kendo) :
        loader(
            'http://cdn.kendostatic.com/2014.1.318/js/kendo.all.min.js',
            function() { doProvide(kendo); });
});
```
На сколько это правильный/оправданный подход?

**Comment by zxqfox** [comment]
@Guria похоже, что у тебя 2 копии jQuery загружается. В остальном — ок
