### ISSUE TITLE
Ребят где скачать то саму библиотеку?

### ISSUE THREAD

**Issue by errogaht** [ymaps/modules#46]
Вроде я программист, вроде неплохо разбираюсь, но чувствую себя полнейшим идиотом - не могу уже пол часа найти КАК НАЧАТЬ то?!?!

Вы написали как пользоваться, но где взять саму библиотеку?
Как я напишу 
script src="YModules.js" type ="text/javascript"
??? где файл то взять??!?! почему нет в readme такой информации, я просто полностью не доумеваю вообще

**Comment by Guria** [comment]
Можно скачать из репозитория или воспользоваться пакетным менеддером npm:
`npm install ym`

**Comment by errogaht** [comment]
простите меня за грубость, просто не выдержал уже, я плохо разбираюсь в Node.js

Спасибо за ответ!
