### ISSUE TITLE
Сравнение с AMD (require.js, webpack)

### ISSUE THREAD

**Issue by DimitryDushkin** [ymaps/modules#47]
Просьба описать use case, когда необходимы асинхронный provide и возможность передекларации модулей. Пока непонятно, зачем эти возможности нужны и чем это решение лучше require.js или webpack.

**Comment by zxqfox** [comment]
http://habrahabr.ru/post/181536/ — тут в комментах интересные тезисы
http://habrahabr.ru/post/213627/ — здесь примеры

**Comment by DimitryDushkin** [comment]
Понял, спасибо) может это стоит вынести в readme? А то библиотека вроде как базовая для bem, вводит еще один велосипед, а обоснования велосипеду нет.

**Comment by zxqfox** [comment]
Хотелось бы, чтобы велосипеда не было, на самом деле. Но чуваки в AMD любят либо все грузить синхронно, либо уносить эту логику в приложение ;-( Либо тупо не понимают, о чем речь идет, занимаясь домашними страничками и разработкой под них стандартов.

**Comment by DimitryDushkin** [comment]
В AMD есть возможность грузить асинхронно в связке с webpack, например, — http://webpack.github.io/docs/code-splitting.html#require-ensure. 

А чего команда AMD "тупо не понимают"?

**Comment by jifeon** [comment]
@zxqfox Как правильно подключить lodash.once например? он зависит от lodash.before, сборки есть только для AMD, CommonJS и es6 модулей. Весь lodash мне не нужен.

**Comment by zxqfox** [comment]
> В AMD есть возможность грузить асинхронно в связке с webpack, например.

@DimitryDushkin Это замусоривает код, имхо. И команде AMD это ок, судя по всему.

> Как правильно подключить lodash.once например? он зависит от lodash.before, сборки есть только для AMD

Если у них уже есть реализации es6, то можно из них собрать ym. См. https://github.com/bem/babel-plugin-bem/issues/3 и сам проект.

Есть еще https://github.com/bem/bem-core/issues/1109

**Comment by jifeon** [comment]
@zxqfox ok спасибо. Вообще конкретно lodash позволяет делать [кастомные сборки](https://lodash.com/custom-builds)

Оставлю это здесь, вдруг кому пригодится:
```bash
#!/usr/bin/env bash

# specify here all the lodash modules you need, separate them by comma
include_modules=once,isPlainObject

# the path we age going to install lodash to
lodash_dir=desktop.blocks/lodash
lodash_path=${lodash_dir}/lodash.js

template='modules.define("lodash", function(provide) {%output% provide(lodash);});'
./node_modules/.bin/lodash include=${include_modules} exports=none iife="${template}" -d -o ${lodash_path} && \
echo "lodash installed successfully";

```
