### ISSUE TITLE
Troubles with babel

### ISSUE THREAD

**Issue by zxqfox** [ymaps/modules#49]
We have to:
```
require('babel/register');
require('desktop.bundles/main-app/main-app.js');
```

But, after babelifying code of `ym` we got `undefined` instead of `this` in global context because of new spec. [The last line](https://github.com/ymaps/modules/blob/master/modules.js#L418) with `this` becomes:
```
})(undefined); // oops ;-(
```

Can we fix that somehow?

Ref: https://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-

**Comment by narqo** [comment]
:+1:

**Comment by zxqfox** [comment]
@dfilatov Thanks for publishing!
